backend/allido_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from users.views import UserCreateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/registration/',
         UserCreateView.as_view(),
         name='registration'),
    path('auth/',
         include('django.contrib.auth.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_error'

backend/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.Homepage.as_view(), name='index'),
    path('about/', views.About.as_view(), name='about'),
    path('rules/', views.Rules.as_view(), name='rules'),
]

backend/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    # path('', views.BirthdayCreateView.as_view(), name='create'),
    # path('list/', views.BirthdayListView.as_view(), name='list'),
    path('profile/<slug:username>/',
         views.UserDetailView.as_view(),
         name='profile'),
    path(
        'edit_profile/',
        views.ProfileUpdateView.as_view(),
        name='edit_profile'
    ),
    # path('<int:pk>/edit/', views.BirthdayUpdateView.as_view(), name='edit'),
    # path('<int:pk>/delete/', views.BirthdayDeleteView.as_view(), name='delete'),
]

backend/core/models.py
from django.db import models

from users.constants import (CLOSE, MAX_VISIBILITY_LENGTH, VISIBILITY_CHOICES)


class ImageAvatarModel(models.Model):
    height_image = models.PositiveIntegerField(default=0)
    width_image = models.PositiveIntegerField(default=0)
    image = models.ImageField(
        'Картинка',
        upload_to='users_images',
        height_field='height_image',
        width_field='width_image',
        blank=True,
    )
    height_avatar = models.PositiveIntegerField(default=0)
    width_avatar = models.PositiveIntegerField(default=0)
    avatar = models.ImageField(
        'Аватарка',
        upload_to='users_images',
        height_field='height_avatar',
        width_field='width_aratar',
        blank=True,
    )

    class Meta:
        abstract = True


class VisibilityDescriptionModel(models.Model):
    description = models.TextField(
        blank=True,
        verbose_name='Описание'
    )
    visibility = models.CharField(
        max_length=MAX_VISIBILITY_LENGTH,
        choices=VISIBILITY_CHOICES,
        default=CLOSE,
        verbose_name='Видимость',
    )

    class Meta:
        abstract = True

backend/events/models.py
from django.db import models

# Create your models here.

backend/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify

from .constants import (ADMIN, MAX_ROLE_LENGTH,
                        MAX_VISIBILITY_IN_GROUP_LENGTH,
                        MODERATOR, ONLY_LOGIN, ROLE_CHOICES, NAME_MAX_LENGHT,
                        VISIBILITY_IN_GROUP_CHOICES, USER)
from core.models import ImageAvatarModel, VisibilityDescriptionModel


class User(AbstractUser, ImageAvatarModel, VisibilityDescriptionModel):
    role = models.CharField(
        max_length=MAX_ROLE_LENGTH,
        choices=ROLE_CHOICES,
        default=USER,
        verbose_name='Роль',
    )
    visibility_in_group = models.CharField(
        max_length=MAX_VISIBILITY_IN_GROUP_LENGTH,
        choices=VISIBILITY_IN_GROUP_CHOICES,
        default=ONLY_LOGIN,
        verbose_name='Видимость в группе',
    )

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('username',)

    def __str__(self):
        return self.username

    @property
    def is_admin(self):
        return self.is_staff or self.is_superuser or self.role == ADMIN

    @property
    def is_moderator(self):
        return self.role == MODERATOR


class Community(ImageAvatarModel, VisibilityDescriptionModel):
    name = models.CharField(
        'Название',
        max_length=NAME_MAX_LENGHT,
    )
    slug = models.SlugField(
        'Идентификатор',
        unique=True,
        help_text=(
            'Идентификатор страницы для URL; '
            'разрешены символы латиницы, цифры, дефис и подчёркивание.'
        ),
    )
    date_created = models.DateTimeField(
        'Дата добавления', auto_now_add=True, db_index=True
    )

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('name',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(User, self).save(*args, **kwargs)

backend/users/forms.py
from typing import Any
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
# import pprint

from .constants import (HEIGHT_IMAGE_MAX_VALUE, IMAGE_MAX_VALUE,
                        WIDTH_IMAGE_MAX_VALUE)

User = get_user_model()


class RegistrationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User


class ProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'avatar', 'image',
                  'email', 'visibility', 'visibility_in_group', 'description')

    def clean_image(self):
        image = self.cleaned_data.get('image', False)
        if image:
            if image.size > IMAGE_MAX_VALUE:
                raise ValidationError("Размер файла слишком большой")
        return image

    def clean_height_image(self):
        height_image = self.cleaned_data.get('height_image', False)
        if height_image:
            if height_image > HEIGHT_IMAGE_MAX_VALUE:
                raise ValidationError("Высота файла слишком большая")
        return height_image

    def clean_width_image(self):
        width_image = self.cleaned_data.get('width_image', False)
        if width_image:
            if width_image > WIDTH_IMAGE_MAX_VALUE:
                raise ValidationError("Ширина файла слишком большая")
        return width_image

backend/events/views.py
from django.shortcuts import render

# Create your views here.

backend/pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class About(TemplateView):
    template_name = 'pages/about.html'


class Rules(TemplateView):
    template_name = 'pages/rules.html'


class Homepage(TemplateView):
    template_name = 'pages/index.html'


def page_not_found(request, exception):
    return render(request, 'pages/404.html', status=404)


def server_error(request):
    return render(request, 'pages/500.html', status=500)


def csrf_failure(request, reason=''):
    return render(request, 'pages/403csrf.html', status=403)

backend/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from .models import User
from .forms import RegistrationForm, ProfileForm


class UserCreateView(CreateView):
    form_class = RegistrationForm
    template_name = 'registration/registration_form.html'
    success_url = reverse_lazy('pages:index')


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'users/edit_profile.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy(
            'users:profile',
            kwargs={'username': self.request.user.username}
        )


class UserDetailView(DetailView):
    model = User
    form_class = ProfileForm
    template_name = 'users/profile.html'

    def get_object(self):
        return get_object_or_404(
            User,
            username=self.kwargs['username'],
        )


class CommunityCreateView(CreateView):
    form_class = RegistrationForm
    template_name = 'registration/registration_form.html'
    success_url = reverse_lazy('pages:index')

backend/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
      {% block title %}ALL I DO{% endblock %}
    </title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> 
  </head>
  <body>
    <div class="d-flex flex-column h-100">
      {% include "includes/header.html" %}
      <div class="container d-flex flex-grow-1">
        <div class="row flex-grow-1 al-bg d-flex pb-0 mt-0 mt-sm-1 ">
          <div class="col-12 col-lg-8 p-1 ">
            <div class="m-0 px-1 py-0 al-bg-dark h-100 ">
              <main>
                <div class="container py-5">
                  {% block content %}{% endblock %}
                </div>
              </main>
            </div>
          </div>
          <div class="col-12 col-lg-4 p-1 ps-0 d-none d-lg-block">
            <div class="m-0 p-2 al-bg-dark h-100">
              {% block body_right %}
                {% include "includes/last_event.html" %}
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
      {% include "includes/footer.html" %}
    </div>
  </body>
</html>

backend/templates/includes/footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center
               py-0 mb-0 mt-1 py-sm-1 my-sm-1 py-lg-2 my-lg-2 border-top">
  {# <p class="col-md-4 mb-0 text-body-secondary">&copy; 2023 VLN, Inc</p> #}
  <ul class="nav col-md-6 justify-content-end">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
  </ul>
  <p>© allido</p>    
</footer>

backend/templates/includes/header.html
{% load static %}
{# top menu #}

<nav class="navbar navbar-expand-sm al-navbar-bg navbar-dark">
  <div class="container-fluid">
      <a href="{% url 'pages:index' %}" class="ms-lg-5 me-2">
          <img src="{% static 'img/logo.png' %}" alt="all i do" height="40">
      </a>
      <a href="{% url 'pages:index' %}" class="navbar-brand me-1 fw-bolder fs-4 ">ALL I DO</a>
      <button class="navbar-toggler " type="button"
              data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Navigation switch">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="navbar-nav flex-fill d-flex flex-wrap justify-content-around mb-2 mb-lg-0 ">
            {% for event_type in event_types %}
              <a href="#" class="al-navbar-text fw-bold  ms-2 me-1 p-2 d-none d-lg-block rounded">
                {{ event_type }}
              </a>
            {% endfor %}
          </div>

          <div class="nav justify-content-center justify-content-sm-end flex-sm-nowrap">
              <a data-bs-toggle="collapse" href="#searchBar" aria-expanded="true"
                 aria-controls="eventTypes" role="button" class="nav-link text-center al-navbar-text rounded">
                {% include "includes/svg/svg_search.html" %} 
              </a>

              {% if user.is_authenticated %}
                  <a class="nav-link text-center al-navbar-text rounded"
                     href="{% url 'users:profile' username=user.username %}">
                    {% include "includes/svg/svg_person_fill.html" %} 
                  </a>
              {% else %}
                  <a class="nav-link text-center al-navbar-text rounded"
                     href="{% url 'login' %}">
                    {% include "includes/svg/svg_person.html" %}
                  </a>
              {% endif %}
          </div>
      </div>
  </div>
</nav>

<div class="row collapse hide me-0 mt-1 mx-0 mb-1 mb-sm-0 mx-sm-3 mx-lg-5" id="searchBar">
  <form class="d-flex" role="search">
      <input class="form-control al-input me-2 ms-sm-1  ms-md-3  ms-lg-5" type="search"
             placeholder="Search"
             aria-label="Search">
      <button class="btn al-navbar-btn me-sm-1 me-md-1 me-lg-5" type="submit">
          'Search'
      </button>
  </form>
</div>

{# end top menu #}   

backend/templates/includes/svg/svg_person.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
     class="bi bi-person" viewBox="0 0 16 16">
  <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"/>
</svg>

backend/templates/includes/svg/svg_person_fill.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
     class="bi bi-person-fill" viewBox="0 0 16 16">
  <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
</svg>

backend/templates/includes/svg/svg_search.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
     class="bi bi-search" viewBox="0 0 16 16">
  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
</svg>

backend/templates/pages/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка CSRF токена{% endblock %}
{% block content %}
  <h1>Ошибка CSRF токена. 403</h1>
  <a href="{% url 'blog:index' %}">Вернуться на главную</a>
{% endblock %}

backend/templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        О проекте
      </div>
      <div class="card-body">
        <p>
          {% lorem b random %}
        </p>
        <p>
          {% lorem b random %}
        </p>
        <p>
          {% lorem b random %}
        </p>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/pages/index.html
{% extends "base.html" %}
{% block title %}
  Main page
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Main page
      </div>
      <div class="card-body">
        <p>
          {% lorem b random %}
        </p>
        <p>
          {% lorem b random %}
        </p>
        <p>
          {% lorem b random %}
        </p>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Правила сайта
      </div>
      <div class="card-body">
        <p>
          <b>First.</b> {% lorem b random %}
        </p>
        <p>
          <b>Second.</b> {% lorem b random %}
        </p>
        <p>
          <b>Third.</b> {% lorem b random %}
        </p>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/users/edit_profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user.username }}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/users/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ object.username }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ object.username }}</h1>
  {% if object.image %}
          <a href="{{ object.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ object.image.url }}">
          </a>
        {% endif %}
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Имя пользователя: {% if object.first_name %}{{ object.first_name }}{% else %}не указано{% endif %}</li>
      <li class="list-group-item text-muted">Регистрация: {{ object.date_joined }}</li>
      <li class="list-group-item text-muted">Роль: {{ object.role }}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == object %}
      <a class="btn btn-sm text-muted" href="{% url 'users:edit_profile' %}">Редактировать профиль</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="btn btn-sm text-muted" href="{% url 'logout' %}">Выйти</a>
      {% endif %}
    </ul>
  </small>
{% endblock %}

backend/templates/users/user_detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user.username }}
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
          href="{% url 'logout' %}">Выйти</a></button>
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}